# Generated by Django 2.2.6 on 2019-10-03 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191003_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='Производитель')),
                ('product_name_model', models.CharField(max_length=50, verbose_name='Имя модели')),
                ('manufacturer_date', models.DateField(null=True, verbose_name='Дата производства')),
                ('product_color', models.CharField(max_length=50, verbose_name='Цвет товара')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость')),
                ('full_name_product', models.CharField(max_length=200, verbose_name='Полное имя продукта')),
                ('currency', models.CharField(choices=[('RUB', ''), ('EUR', ''), ('USD', '')], max_length=3)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.CategoryProduct', to_field='category_url', verbose_name='Категория продукта')),
            ],
        ),
    ]
