# Generated by Django 2.2.6 on 2019-10-03 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191003_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.User')),
                ('state_wallet', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Состояние счета')),
                ('currency', models.CharField(choices=[('RUB', ''), ('EUR', ''), ('USD', '')], max_length=3)),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения счета')),
            ],
        ),
    ]
