# Generated by Django 2.2.6 on 2019-10-13 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191003_1121'),
    ]

    operations = [
      migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_addr_user', models.CharField(max_length=200, verbose_name='Почтовый адрес')),
                ('count', models.IntegerField(verbose_name='Колличество товара')),
                ('place_of_order', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время оформления заказа')),
                ('order_status', models.BooleanField(choices=[(False, 'canceled'), (True, 'active')], default=False, verbose_name='Статус заказа')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость')),
                ('product', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),  
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='comment_to_order',
            field=models.CharField(default=1, max_length=300, verbose_name='Комментарий к заказу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='category_url',
            field=models.SlugField(unique=True, verbose_name='ЧПУ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.IntegerField(verbose_name='Количество товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('RUB', 'rub'), ('EUR', 'eur'), ('USD', 'usd')], max_length=3),
        ),
    ]
