# Generated by Django 2.2.6 on 2019-10-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userwallet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='userwallet',
            options={'verbose_name': 'Кошелек', 'verbose_name_plural': 'Кошельки'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='mailing_addr_user',
        ),
        migrations.AddField(
            model_name='order',
            name='comment_to_order',
            field=models.CharField(default=0, max_length=300, verbose_name='Комментарий к заказу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='category_url',
            field=models.SlugField(unique=True, verbose_name='ЧПУ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.IntegerField(verbose_name='Количество товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('RUB', 'rub'), ('EUR', 'eur'), ('USD', 'usd')], max_length=3),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='currency',
            field=models.CharField(choices=[('RUB', 'rub'), ('EUR', 'eur'), ('USD', 'usd')], max_length=3),
        ),
    ]
