# Generated by Django 2.2.6 on 2019-10-07 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191005_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mailing_addr_user',
            field=models.CharField(default='Saratov Sity street Chernyshewskoko 101', max_length=200, verbose_name='Почтовый адрес'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='api.Product'),
            preserve_default=False,
        ),
    ]
